In [ ]:
%reload_ext autoreload
%autoreload 2

In [ ]:
# this panel tests random noise as a cirtcuit
# it has an infinite loop. It should just be disqualified. 


from CircuitSimulation.CircuitSimulator import *
import numpy as np


sampleImg = np.array([
       [0, 1, 3, 1, 2, 1, 2, 0, 3, 0],
       [3, 2, 0, 3, 3, 1, 2, 1, 1, 1],
       [0, 0, 2, 1, 1, 1, 3, 3, 1, 3],
       [2, 2, 1, 1, 1, 2, 3, 0, 1, 3],
       [1, 3, 0, 1, 0, 0, 0, 0, 0, 0],
       [3, 1, 0, 2, 1, 1, 3, 1, 1, 0],
       [3, 2, 0, 0, 0, 0, 3, 1, 2, 3],
       [2, 0, 1, 3, 3, 2, 1, 0, 2, 0],
       [2, 3, 2, 0, 2, 0, 0, 1, 2, 1],
       [0, 3, 2, 0, 0, 3, 3, 1, 1, 1]])


inpSockets = [
    (Socket("inp0", True), (0, 0)), 
    (Socket("inp1", True), (0, 3)), 
    (Socket("inp2", True), (0, 6)), 
    (Socket("inp3", True), (0, 9)), 
]

outSockets = [  
	(Socket("out0", False), (9, 0)), 
    (Socket("out1", False), (9, 3)), 
    (Socket("out2", False), (9, 6)), 
    (Socket("out3", False), (9, 9)),
]

socketMap, WireSets = GetSocketMap(sampleImg, inpSockets + outSockets)
print(WireSets)
connectionMap = GetConnectionMap(socketMap)
print(socketMap)

order = [inpSockets[i] for i in (0, 1)]
Simulate(connectionMap, socketMap, order)

[[0 1 2 3 3 3 4 0 5 0]
 [6 1 0 3 3 3 4 5 5 5]
 [0 0 3 3 3 3 4 5 5 5]
 [7 8 3 3 3 3 4 0 5 5]
 [7 8 0 3 0 0 0 0 0 0]
 [7 8 0 3 9 9 10 11 11 0]
 [7 8 0 0 0 0 10 11 11 12]
 [7 0 13 14 15 16 10 0 11 0]
 [7 17 13 0 15 0 0 11 11 11]
 [0 17 13 0 0 18 19 11 11 11]]
{inp0: {1, 6}, inp1: {8, 7}, inp2: {8, 7}, inp3: {17, 7}, out0: {5}, out1: {5}, out2: {11}, out3: {11}, NAND0base: {1}, NAND0collector: set(), NAND0emitter: {3}, AND1base: {3}, AND1collector: {3}, AND1emitter: {3}, AND2base: {3}, AND2collector: {4}, AND2emitter: set(), NAND3base: set(), NAND3collector: {5}, NAND3emitter: set(), NAND4base: set(), NAND4collector: set(), NAND4emitter: {1}, AND5base: {6}, AND5collector: {1}, AND5emitter: set(), NAND6base: set(), NAND6collector: {3}, NAND6emitter: {3}, NAND7base: {3}, NAND7collector: {3}, NAND7emitter: {3}, AND8base: {3}, AND8collector: {4}, AND8emitter: {5}, AND9base: set(), AND9collector: {3}, AND9emitter: {3}, NAND10base: {3}, NAND10collector: {4}, NAND10emitter: {5}, NAND11base: {4}, 

Exception: Maximum recursion depth of 51 exceeded

___

In [42]:
from CircuitSimulation.CircuitSimulator import *
import numpy as np


sampleImg = np.array(
    [
        [0, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 1, 1, 3, 1, 1],
        [1, 1, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
    ]
)

socket1 = Socket("inp0", True)
socket2 = Socket("inp1", True)
socket3 = Socket("out0", False)

socketList = [
    (socket1, (0, 1)), 
    (socket2, (0, 5)), 
    (socket3, (7, 3)),  
    ]

socketMap = GetSocketMap(sampleImg, socketList)
connectionMap = GetConnectionMap(socketMap)
print(socketMap)

testOrder1 = []
Simulate(connectionMap, socketMap, testOrder1)


{inp0: {1}, inp1: {3}, out0: {2}, NAND0base: {3}, NAND0collector: {1}, NAND0emitter: {2}}


[(inp0, False), (inp1, False), (out0, True)]

In [27]:
testSet = set()
testSet.add(())
testSet

{()}

In [31]:
bool(False * False)

False